### ISSUE TITLE
DUEL NAVI

### ISSUE THREAD

**Issue by INH888** [Mr-MIBonk/M.I.B._More-Incredible-Bash#176]
Dude, I have a new problem, there is a problem with the dual navigator, as shown in the image ...

![20230413143641](https://user-images.githubusercontent.com/130017774/231676527-3baf0c72-78e5-4d13-8336-dbd206bbc3fc.jpg)
![20230413143654](https://user-images.githubusercontent.com/130017774/231676544-c61a5976-d7f4-4658-9eb6-c254cdb53d68.jpg)

**Comment by harman-f** [comment]
Need to see your train. 
best upload log file.

**Comment by INH888** [comment]
> Need to see your train. best upload log file.

[MU1102-AW7-MON22.06.1700062600.log](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/files/11228960/MU1102-AW7-MON22.06.1700062600.log)

**Comment by harman-f** [comment]
Get latest version from repo: https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/archive/refs/heads/main.zip
And report back

**Comment by INH888** [comment]
> Get latest version from repo: https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/archive/refs/heads/main.zip And report back

[MU1102-AW7-MON22.06.1700062600.log](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/files/11238756/MU1102-AW7-MON22.06.1700062600.log)

**Comment by harman-f** [comment]
get fresh version, should work now

**Comment by INH888** [comment]
> get fresh version, should work now

Still not working T.T
[MU1102-AW7-MON22.06.1700062600.log](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/files/11241186/MU1102-AW7-MON22.06.1700062600.log)

**Comment by INH888** [comment]
> get fresh version, should work now

Master，Have new progress?
